
package ec.udu.ups.appdis.agenda.testsoap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-23T10:21:48.940-05:00
 * Generated source version: 2.7.11
 * 
 */
public final class PersonasServicesSOAP_PersonasServicesSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.agenda.appdis.ups.udu.ec/", "PersonasServicesSOAPService");

    private PersonasServicesSOAP_PersonasServicesSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PersonasServicesSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PersonasServicesSOAPService ss = new PersonasServicesSOAPService(wsdlURL, SERVICE_NAME);
        PersonasServicesSOAP port = ss.getPersonasServicesSOAPPort();  
        
        {
        System.out.println("Invoking saludar...");
        java.lang.String _saludar_arg0 = "SoyJUANc";
        java.lang.String _saludar__return = port.saludar(_saludar_arg0);
        System.out.println("saludar.result=" + _saludar__return);


        }
        {
        System.out.println("Invoking deposito...");
        java.lang.String _deposito_arg0 = "";
        double _deposito_arg1 = 0.0;
        java.lang.String _deposito__return = port.deposito(_deposito_arg0, _deposito_arg1);
        System.out.println("deposito.result=" + _deposito__return);


        }
        {
        System.out.println("Invoking listaPersonas...");
        java.util.List<ec.udu.ups.appdis.agenda.testsoap.Persona> _listaPersonas__return = port.listaPersonas();
        System.out.println("listaPersonas.result=" + _listaPersonas__return);


        }

        System.exit(0);
    }

}
