package ec.udu.ups.appdis.agenda.testsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-23T10:21:48.991-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://services.agenda.appdis.ups.udu.ec/", name = "PersonasServicesSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonasServicesSOAP {

    @WebMethod
    @RequestWrapper(localName = "saludar", targetNamespace = "http://services.agenda.appdis.ups.udu.ec/", className = "ec.udu.ups.appdis.agenda.testsoap.Saludar")
    @ResponseWrapper(localName = "saludarResponse", targetNamespace = "http://services.agenda.appdis.ups.udu.ec/", className = "ec.udu.ups.appdis.agenda.testsoap.SaludarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String saludar(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deposito", targetNamespace = "http://services.agenda.appdis.ups.udu.ec/", className = "ec.udu.ups.appdis.agenda.testsoap.Deposito")
    @ResponseWrapper(localName = "depositoResponse", targetNamespace = "http://services.agenda.appdis.ups.udu.ec/", className = "ec.udu.ups.appdis.agenda.testsoap.DepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String deposito(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "listaPersonas", targetNamespace = "http://services.agenda.appdis.ups.udu.ec/", className = "ec.udu.ups.appdis.agenda.testsoap.ListaPersonas")
    @ResponseWrapper(localName = "listaPersonasResponse", targetNamespace = "http://services.agenda.appdis.ups.udu.ec/", className = "ec.udu.ups.appdis.agenda.testsoap.ListaPersonasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.udu.ups.appdis.agenda.testsoap.Persona> listaPersonas();
}
