package ec.edu.ups.appdis.bancaSOAP;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-24T13:36:29.401-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://servis.proyecto.ups.edu.ec/", name = "BancaWebServicesSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface BancaWebServicesSOAP {

    @WebMethod
    @RequestWrapper(localName = "buscaClienteID", targetNamespace = "http://servis.proyecto.ups.edu.ec/", className = "ec.edu.ups.appdis.bancaSOAP.BuscaClienteID")
    @ResponseWrapper(localName = "buscaClienteIDResponse", targetNamespace = "http://servis.proyecto.ups.edu.ec/", className = "ec.edu.ups.appdis.bancaSOAP.BuscaClienteIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.edu.ups.appdis.bancaSOAP.Cliente buscaClienteID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "transferencia", targetNamespace = "http://servis.proyecto.ups.edu.ec/", className = "ec.edu.ups.appdis.bancaSOAP.Transferencia")
    @ResponseWrapper(localName = "transferenciaResponse", targetNamespace = "http://servis.proyecto.ups.edu.ec/", className = "ec.edu.ups.appdis.bancaSOAP.TransferenciaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String transferencia();

    @WebMethod
    @RequestWrapper(localName = "deposito", targetNamespace = "http://servis.proyecto.ups.edu.ec/", className = "ec.edu.ups.appdis.bancaSOAP.Deposito")
    @ResponseWrapper(localName = "depositoResponse", targetNamespace = "http://servis.proyecto.ups.edu.ec/", className = "ec.edu.ups.appdis.bancaSOAP.DepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String deposito(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "retiro", targetNamespace = "http://servis.proyecto.ups.edu.ec/", className = "ec.edu.ups.appdis.bancaSOAP.Retiro")
    @ResponseWrapper(localName = "retiroResponse", targetNamespace = "http://servis.proyecto.ups.edu.ec/", className = "ec.edu.ups.appdis.bancaSOAP.RetiroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String retiro();
}
