
package ec.edu.ups.appdis.bancaSOAP;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-24T13:36:29.343-05:00
 * Generated source version: 2.7.11
 * 
 */
public final class BancaWebServicesSOAP_BancaWebServicesSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://servis.proyecto.ups.edu.ec/", "BancaWebServicesSOAPService");

    private BancaWebServicesSOAP_BancaWebServicesSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BancaWebServicesSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BancaWebServicesSOAPService ss = new BancaWebServicesSOAPService(wsdlURL, SERVICE_NAME);
        BancaWebServicesSOAP port = ss.getBancaWebServicesSOAPPort();  
        
        {
        System.out.println("Invoking buscaClienteID...");
        java.lang.String _buscaClienteID_arg0 = "";
        ec.edu.ups.appdis.bancaSOAP.Cliente _buscaClienteID__return = port.buscaClienteID(_buscaClienteID_arg0);
        System.out.println("buscaClienteID.result=" + _buscaClienteID__return);


        }
        {
        System.out.println("Invoking transferencia...");
        java.lang.String _transferencia__return = port.transferencia();
        System.out.println("transferencia.result=" + _transferencia__return);


        }
        {
        System.out.println("Invoking deposito...");
        java.lang.String _deposito_arg0 = "0106805419";
        double _deposito_arg1 = 5000.0;
        java.lang.String _deposito__return = port.deposito(_deposito_arg0, _deposito_arg1);
        System.out.println("deposito.result=" + _deposito__return);


        }
        {
        System.out.println("Invoking retiro...");
        java.lang.String _retiro__return = port.retiro();
        System.out.println("retiro.result=" + _retiro__return);


        }

        System.exit(0);
    }

}
