package com.jonathan.modelo;
// Generated 06/07/2016 10:40:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="bd_venta"
)
public class Producto  implements java.io.Serializable {


     private Integer prodId;
     private String prodNombre;
     private Integer prodCant;
     private Double prodPrecio;
     private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);

    public Producto() {
    }

    public Producto(String prodNombre, Integer prodCant, Double prodPrecio, Set<DetalleVenta> detalleVentas) {
       this.prodNombre = prodNombre;
       this.prodCant = prodCant;
       this.prodPrecio = prodPrecio;
       this.detalleVentas = detalleVentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="prod_id", unique=true, nullable=false)
    public Integer getProdId() {
        return this.prodId;
    }
    
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }

    
    @Column(name="prod_nombre", length=100)
    public String getProdNombre() {
        return this.prodNombre;
    }
    
    public void setProdNombre(String prodNombre) {
        this.prodNombre = prodNombre;
    }

    
    @Column(name="prod_cant")
    public Integer getProdCant() {
        return this.prodCant;
    }
    
    public void setProdCant(Integer prodCant) {
        this.prodCant = prodCant;
    }

    
    @Column(name="prod_precio", precision=8)
    public Double getProdPrecio() {
        return this.prodPrecio;
    }
    
    public void setProdPrecio(Double prodPrecio) {
        this.prodPrecio = prodPrecio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


